tags:
  - name: Requests
    description: staff management Api
paths:
  /{phoneNumber}/staff:
    # [GET] staffs
    get:
      tags:
        - Requests
      summary: Getting all the staff data
      parameters:
        - name: phoneNumber
          in: path
          description: Phone number
          required: true
          type: integer
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
        404:
          description: "Not Found"
        400:
          description: "Bad request"

    # [POST] add staff
    post:
      tags:
        - Requests
      summary: Adding staff
      parameters:
        - name: phoneNumber
          in: path
          description: Phone number
          required: true
          type: integer
        - name: body
          in: body
          description: staff Data
          required: true
          schema:
            $ref: "#/definitions/staff"
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
        404:
          description: "Not Found"
        400:
          description: "Bad request"

  /{phoneNumber}/staff/{employeeId}:
    # [GET] staff by id
    get:
      tags:
        - Requests
      summary: Getting the staff by id
      parameters:
        - name: phoneNumber
          in: path
          description: Phone number
          required: true
          type: integer
        - name: id
          in: path
          description: staff id
          required: true
          type: string
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
        404:
          description: "Not Found"
        400:
          description: "Bad request"

    # [PUT] update staff by id
    put:
      tags:
        - Requests
      summary: Updating staff using id
      parameters:
        - name: phoneNumber
          in: path
          description: phone number
          required: true
          type: integer
        - name: id
          in: path
          description: unique id of staff
          required: true
          type: string
        - name: body
          in: body
          description: staff data to update
          required: true
          type: string
          schema:
            $ref: "#/definitions/staff"
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
        404:
          description: "Not Found"
        400:
          description:
            "Bad request"

    # [POST] add vacation
    post:
      tags:
        - Requests
      summary: Adding staff
      parameters:
        - name: phoneNumber
          in: path
          description: Phone number
          required: true
          type: integer
        - name: employeeId
          in: path
          description: Employee id
          required: true
          type: integer
        - name: body
          in: body
          description: staff Data
          required: true
          schema:
            $ref: "#/definitions/staff"
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
        404:
          description: "Not Found"
        400:
          description: "Bad request"

    # [DELETE] delete staff by id
    delete:
      tags:
        - Requests
      summary: Deleting staff using id
      parameters:
        - name: phoneNumber
          in: path
          description: phone number
          required: true
          type: integer
        - name: id
          in: path
          description: unique id of staff
          required: true
          type: string
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
        404:
          description: "Not Found"
        400:
          description: "Bad request"

  /{phoneNumber}/staff/{employeeId}/vacation:

    # [GET] vacation by id
    get:
      tags:
        - Requests
      summary: Getting the vacation by id
      parameters:
        - name: phoneNumber
          in: path
          description: Phone number
          required: true
          type: integer
        - name: employeeId
          in: path
          description: staff id
          required: true
          type: string
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
        404:
          description: "Not Found"
        400:
          description: "Bad request"




   # [DELETE] delete vacation by id
    delete:
      tags:
        - Requests
      summary: Deleting vacation using id
      parameters:
        - name: phoneNumber
          in: path
          description: phone number
          required: true
          type: integer
        - name: id
          in: path
          description: unique id of staff
          required: true
          type: string
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
        404:
          description: "Not Found"
        400:
          description: "Bad request"


# definitions
definitions:
  staff:
    type: object
    required:
      - name
      - age
      - phoneNumber
      - joiningDate
      - designation
      - emailId
      - status
      - emp_id

    properties:
      name:
        type: string
        description:
      age:
        type: string
        description:
      phoneNumber:
        type: string
        description:
      joiningDate:
        type: integer
        description:
      designation:
        type: string
        description:
      emailId:
        type: string
        description:
      status:
        type: string
        description:
